data: '../data/item_summary_all/preprocessed/'
logF: 'experiments/'
#refF: '/home/linjunyang/en_vi/valid.tgt'
tensorboard: True
tensorboard_log_dir: 'experiments/'
epoch: 100
batch_size: 48
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
param_init: 0
param_init_glorot: True
learning_rate: 1
max_grad_norm: 1
learning_rate_decay: 0.95
start_decay_steps: 10000
warmup_steps: 16000
decay_method: "noam"
beta1: 0.9
beta2: 0.998
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 2
bidirectional: True
dropout: 0.4
emb_dropout: 0.1
max_time_step: 150
report_interval: 100
eval_interval: 1000
save_interval: 10000
metrics: ['bleu']
shared_vocab: False
beam_size: 1
unk: True
schedule: False
selfatt: False
schesamp: False
swish: False
length_norm: True
heads: 8
d_ff: 2048
label_smoothing: 0.1
positional: True
convolutional: False
rl: True
rl_coef: 10
ctr_rewared_provider_path: 'experiments/ctr_reward_provider.pt'
baseline: 'self_critic'
