data: '/home/linjunyang/pku/data/'
logF: 'experiments/cn_en/'
refF: '/home/linjunyang/nist/nist02.tok.ref'
tensorboard: True
tensorboard_log_dir: 'experiments/cn_en/tensorboard'
epoch: 50
batch_size: 84
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
param_init: 0
param_init_glorot: True
learning_rate: 2
max_grad_norm: 0
learning_rate_decay: 0.5
start_decay_steps: 10000
warmup_steps: 16000
decay_method: "noam"
beta1: 0.9
beta2: 0.998
emb_size: 512
hidden_size: 512
dec_num_layers: 6
enc_num_layers: 6
bidirectional: True
dropout: 0.1
max_time_step: 100
report_interval: 100
eval_interval: 10000
save_interval: 3000
metrics: ['bleu']
shared_vocab: False
beam_size: 1
unk: False
schedule: False
selfatt: False
schesamp: False
swish: False
length_norm: True
heads: 8
d_ff: 2048
label_smoothing: 0.1