data: '/home/linjunyang/en_de_bpe/data/data/'
logF: 'experiments/en_de_bpe/'
refF: '/home/linjunyang/en_de/valid.tgt'
tensorboard: True
tensorboard_log_dir: 'experiments/en_de_bpe/tensorboard1'
epoch: 50
batch_size: 64
valid_batch_size: 32
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
param_init: 0
param_init_glorot: False
learning_rate: 2
max_grad_norm: 0
learning_rate_decay: 0.5
start_decay_steps: 10000
warmup_steps: 16000
decay_method: "noam"
beta1: 0.9
beta2: 0.998
emb_size: 512
hidden_size: 512
dec_num_layers: 6
enc_num_layers: 6
bidirectional: True
dropout: 0.1
max_time_step: 150
report_interval: 100
eval_interval: 10000
save_interval: 9000
metrics: ['bleu']
shared_vocab: True
beam_size: 1
unk: True
schedule: False
selfatt: False
schesamp: False
swish: False
length_norm: True
heads: 8
d_ff: 2048
label_smoothing: 0.1
positional: True