data: '/home/linjunyang/en_vi/data/'
logF: 'experiments/en_vi/'
refF: '/home/linjunyang/en_vi/valid.tgt'
tensorboard: True
tensorboard_log_dir: 'experiments/en_vi/tensorboard'
epoch: 100
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
param_init: 0
param_init_glorot: True
learning_rate: 2
max_grad_norm: 0
learning_rate_decay: 0.5
start_decay_steps: 10000
warmup_steps: 16000
decay_method: "noam"
beta1: 0.9
beta2: 0.998
emb_size: 512
hidden_size: 512
dec_num_layers: 1
enc_num_layers: 1
bidirectional: True
dropout: 0.4
emb_dropout: 0.1
max_time_step: 150
report_interval: 100
eval_interval: 500
save_interval: 5000
save_individual: 300000
metrics: ['bleu']
shared_vocab: False
beam_size: 1
unk: True
schedule: False
selfatt: False
schesamp: False
swish: False
length_norm: True
heads: 8
d_ff: 2048
label_smoothing: 0.1
positional: True
convolutional: False
rl: False
reward: "f1"
baseline: "self_critic"
rl_coef: 0.7