data: '/home/linjunyang/multilabel_rcv/data/'
logF: 'experiments/rcv/'
# refF: '/home/linjunyang/en_vi/valid.tgt'
tensorboard: True
tensorboard_log_dir: 'experiments/rcv/tensorboard/'
epoch: 10
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
param_init: 0
param_init_glorot: False
learning_rate: 0.0003
max_grad_norm: 10
learning_rate_decay: 0.5
start_decay_steps: 4000
start_decay_at: 2
warmup_steps: 16000
decay_method: "normal"
beta1: 0.9
beta2: 0.999
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 2
bidirectional: True
dropout: 0.2
emb_dropout: 0
max_time_step: 15
report_interval: 100
eval_interval: 500
save_interval: 5000
save_individual: 30000
metrics: ['hamming_loss', 'macro_f1', 'micro_f1']
shared_vocab: False
beam_size: 5
unk: False
length_norm: True
heads: 8
d_ff: 2048
label_smoothing: 0
positional: True
convolutional: False
reward: "f1"
baseline: "self_critic"
rl_coef: 0.7
