data: '/apsarapangu/disk2/shuangqing.ljy/data/know_card/title_summary_item/filter/data/'
logF: 'experiments/title_summary_item_filter/'
#refF: '/home/linjunyang/en_vi/valid.tgt'
tensorboard: True
tensorboard_log_dir: 'experiments/title_summary_item_filter/tensorboard/'
epoch: 20
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
param_init: 0.04
param_init_glorot: False
learning_rate: 1
max_grad_norm: 1
learning_rate_decay: 0.95
start_decay_steps: 10000
warmup_steps: 4000
decay_method: "noam"
beta1: 0.9
beta2: 0.998
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 2
bidirectional: True
dropout: 0.1
emb_dropout: 0.1
max_time_step: 150
report_interval: 100
eval_interval: 5000
save_interval: 3000
metrics: ['bleu']
shared_vocab: False
beam_size: 1
unk: True
schedule: False
selfatt: False
schesamp: False
swish: False
length_norm: True
heads: 8
d_ff: 2048
label_smoothing: 0
positional: True
convolutional: False
rl: True
reward: "f1"
baseline: "self_critic"
rl_coef: 0.7
